### ISSUE TITLE
Cannot change output tempo

### ISSUE THREAD

**Issue by droussis** [walkywalker/automix#1]
Hi,
Although Automix works, it is "locked" on 87.5 BPM since I can't change the output tempo with the -ot argument.

For example, the following command works:
> ./automix -i experiment/ -o results/exp3.mp3 -m -bd 5 -dd 5 -it 100 -l 5 -s 8232

but not the following:
> ./automix -i experiment/ -o results/exp3.mp3 -m -bd 5 -dd 5 -it 100 -l 5 -s 8232 -ot 125

It outputs the following error message: 

> terminate called after throwing an instance of 'std::invalid_argument'
> what():  stod
>Aborted (core dumped)

Thank you!

**Comment by walkywalker** [comment]
Fixed in 8312da65b3a60cd177e0673ec624cb863526fbb8
